//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-02 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\Ana Gomes\\Documents\\git\\mfes-amazonas\\ficheiros em rtf\\Piece.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Token;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Piece implements EvaluatePP {


// ***** VDMTOOLS START Name=Position KEEP=NO
  public static class Position implements Record {

    public Number x;

    public Number y;


    public Position () {}


    public Position (Number p1, Number p2) {
      x = p1;
      y = p2;
    }


    public Object clone () {
      return new Position(x, y);
    }


    public String toString () {
      return "mk_Piece`Position(" + UTIL.toString(x) + ", " + UTIL.toString(y) + ")";
    }


    public boolean equals (Object obj) {
      if (!(obj instanceof Position)) 
        return false;
      else {
        Position temp = (Position)obj;
        return UTIL.equals(x, temp.x) && UTIL.equals(y, temp.y);
      }
    }


    public int hashCode () {
      return (x == null ? 0 : x.hashCode()) + (y == null ? 0 : y.hashCode());
    }

  }
// ***** VDMTOOLS END Name=Position
;

// ***** VDMTOOLS START Name=position KEEP=NO
  private volatile Position position = null;
// ***** VDMTOOLS END Name=position

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=PieceSentinel KEEP=NO
  class PieceSentinel extends Sentinel {

    public final int GetX = 0;

    public final int GetY = 1;

    public final int SetX = 2;

    public final int SetY = 3;

    public final int Piece = 4;

    public final int nr_functions = 5;


    public PieceSentinel () throws CGException {}


    public PieceSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=PieceSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new PieceSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=inv_Position#1|Position KEEP=NO
  static public Boolean inv_Position (final Position p) throws CGException {
    Boolean varRes_2 = null;
    Boolean var1_3 = null;
    Boolean var1_4 = null;
    if ((var1_4 = Boolean.valueOf((p.x).intValue() >= 0)).booleanValue()) 
      var1_4 = Boolean.valueOf((p.x).intValue() < 10);
    if ((var1_3 = var1_4).booleanValue()) 
      var1_3 = Boolean.valueOf((p.y).intValue() >= 0);
    if ((varRes_2 = var1_3).booleanValue()) 
      varRes_2 = Boolean.valueOf((p.y).intValue() <= 10);
    return varRes_2;
  }
// ***** VDMTOOLS END Name=inv_Position#1|Position


// ***** VDMTOOLS START Name=vdm_init_Piece KEEP=NO
  private void vdm_init_Piece () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Piece


// ***** VDMTOOLS START Name=Piece KEEP=NO
  public Piece () throws CGException {
    vdm_init_Piece();
  }
// ***** VDMTOOLS END Name=Piece


// ***** VDMTOOLS START Name=Piece#2|Number|Number KEEP=NO
  public Piece (final Number x, final Number y) throws CGException {
    vdm_init_Piece();
    Position rhs_6 = new Position(x, y);
    if (!(((Object)rhs_6) instanceof Record)) 
      UTIL.RunTime("Incompatible type");
    position = (Position)UTIL.clone(rhs_6);
  }
// ***** VDMTOOLS END Name=Piece#2|Number|Number


// ***** VDMTOOLS START Name=SetX#1|Number KEEP=NO
  public void SetX (final Number x) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).SetX);
    try {
      if (position instanceof Position) 
        ((Position)position).x = x;
      else 
        UTIL.RunTime("An object or record was expected");
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).SetX);
    }
  }
// ***** VDMTOOLS END Name=SetX#1|Number


// ***** VDMTOOLS START Name=SetY#1|Number KEEP=NO
  public void SetY (final Number y) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).SetY);
    try {
      if (position instanceof Position) 
        ((Position)position).y = y;
      else 
        UTIL.RunTime("An object or record was expected");
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).SetY);
    }
  }
// ***** VDMTOOLS END Name=SetY#1|Number


// ***** VDMTOOLS START Name=GetX KEEP=NO
  public Number GetX () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).GetX);
    try {
      return (position.x);
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).GetX);
    }
  }
// ***** VDMTOOLS END Name=GetX


// ***** VDMTOOLS START Name=GetY KEEP=NO
  public Number GetY () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).GetY);
    try {
      return (position.y);
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).GetY);
    }
  }
// ***** VDMTOOLS END Name=GetY

}
;
