//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-04 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\Ana Gomes\\Documents\\git\\mfes-amazonas\\ficheiros em rtf\\TestBoard.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Map;
import java.util.HashMap;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class TestBoard implements EvaluatePP {

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=TestBoardSentinel KEEP=NO
  class TestBoardSentinel extends Sentinel {

    public final int AssertTrue = 0;

    public final int AssertFalse = 1;

    public final int TestBoardMove = 2;

    public final int TestBoardGameOver = 3;

    public final int TestBoardPathFree = 4;

    public final int TestBoardSetArrow = 5;

    public final int TestBoardMoveValid = 6;

    public final int nr_functions = 7;


    public TestBoardSentinel () throws CGException {}


    public TestBoardSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=TestBoardSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new TestBoardSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_TestBoard KEEP=NO
  private void vdm_init_TestBoard () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_TestBoard


// ***** VDMTOOLS START Name=TestBoard KEEP=NO
  public TestBoard () throws CGException {
    vdm_init_TestBoard();
  }
// ***** VDMTOOLS END Name=TestBoard


// ***** VDMTOOLS START Name=AssertTrue#1|Boolean KEEP=NO
  public void AssertTrue (final Boolean a) throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).AssertTrue);
    try {
      if (!this.pre_AssertTrue(a).booleanValue()) 
        UTIL.RunTime("Precondition failure in AssertTrue");
      return;
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).AssertTrue);
    }
  }
// ***** VDMTOOLS END Name=AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=pre_AssertTrue#1|Boolean KEEP=NO
  public Boolean pre_AssertTrue (final Boolean a) throws CGException {
    return a;
  }
// ***** VDMTOOLS END Name=pre_AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=AssertFalse#1|Boolean KEEP=NO
  public void AssertFalse (final Boolean a) throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).AssertFalse);
    try {
      if (!this.pre_AssertFalse(a).booleanValue()) 
        UTIL.RunTime("Precondition failure in AssertFalse");
      return;
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).AssertFalse);
    }
  }
// ***** VDMTOOLS END Name=AssertFalse#1|Boolean


// ***** VDMTOOLS START Name=pre_AssertFalse#1|Boolean KEEP=NO
  public Boolean pre_AssertFalse (final Boolean a) throws CGException {
    return Boolean.valueOf(UTIL.equals(a, Boolean.FALSE));
  }
// ***** VDMTOOLS END Name=pre_AssertFalse#1|Boolean


// ***** VDMTOOLS START Name=TestBoardMoveValid KEEP=NO
  public void TestBoardMoveValid () throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).TestBoardMoveValid);
    try {
      Board b = new Board();
      AssertTrue(b.moveIsValid(new Integer(0), new Integer(7)));
      AssertTrue(b.moveIsValid(new Integer(2), new Integer(0)));
      AssertTrue(b.moveIsValid(new Integer(2), new Integer(2)));
      AssertFalse(b.moveIsValid(new Integer(0), new Integer(0)));
      AssertFalse(b.moveIsValid(new Integer(2), new Integer(3)));
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).TestBoardMoveValid);
    }
  }
// ***** VDMTOOLS END Name=TestBoardMoveValid


// ***** VDMTOOLS START Name=TestBoardPathFree KEEP=NO
  public void TestBoardPathFree () throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).TestBoardPathFree);
    try {
      Board b = new Board();
      Map positions = new HashMap();
      AssertFalse(b.pathIsFree(new Integer(0), new Integer(3), new Integer(2), new Integer(6)));
      AssertTrue(b.pathIsFree(new Integer(0), new Integer(3), new Integer(0), new Integer(5)));
      AssertTrue(b.pathIsFree(new Integer(0), new Integer(3), new Integer(3), new Integer(3)));
      AssertTrue(b.pathIsFree(new Integer(0), new Integer(3), new Integer(1), new Integer(4)));
      AssertFalse(b.pathIsFree(new Integer(0), new Integer(3), new Integer(0), new Integer(7)));
      AssertTrue(b.pathIsFree(new Integer(0), new Integer(3), new Integer(5), new Integer(8)));
      Map rhs_37 = new HashMap();
      rhs_37.put(new Piece.Position(new Integer(0), new Integer(4)), new Arrow(new Integer(0), new Integer(4)));
      rhs_37.put(new Piece.Position(new Integer(1), new Integer(4)), new Arrow(new Integer(1), new Integer(4)));
      rhs_37.put(new Piece.Position(new Integer(0), new Integer(3)), new Amazon(new Integer(0), new Integer(3), new quotes.White()));
      rhs_37.put(new Piece.Position(new Integer(0), new Integer(7)), new Amazon(new Integer(0), new Integer(7), new quotes.Black()));
      positions = (Map)UTIL.clone(rhs_37);
      b.setPositions(positions);
      AssertFalse(b.pathIsFree(new Integer(0), new Integer(3), new Integer(2), new Integer(5)));
      Map rhs_72 = new HashMap();
      rhs_72.put(new Piece.Position(new Integer(1), new Integer(3)), new Arrow(new Integer(1), new Integer(3)));
      rhs_72.put(new Piece.Position(new Integer(0), new Integer(3)), new Amazon(new Integer(0), new Integer(3), new quotes.White()));
      rhs_72.put(new Piece.Position(new Integer(0), new Integer(7)), new Amazon(new Integer(0), new Integer(7), new quotes.Black()));
      positions = (Map)UTIL.clone(rhs_72);
      b.setPositions(positions);
      AssertFalse(b.pathIsFree(new Integer(0), new Integer(3), new Integer(2), new Integer(3)));
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).TestBoardPathFree);
    }
  }
// ***** VDMTOOLS END Name=TestBoardPathFree


// ***** VDMTOOLS START Name=TestBoardMove KEEP=NO
  public void TestBoardMove () throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).TestBoardMove);
    try {
      Board b = new Board();
      Map positions = new HashMap();
      positions.put(new Piece.Position(new Integer(1), new Integer(1)), new Arrow(new Integer(1), new Integer(1)));
      positions.put(new Piece.Position(new Integer(2), new Integer(1)), new Arrow(new Integer(2), new Integer(1)));
      positions.put(new Piece.Position(new Integer(0), new Integer(0)), new Amazon(new Integer(0), new Integer(0), new quotes.White()));
      positions.put(new Piece.Position(new Integer(0), new Integer(3)), new Amazon(new Integer(0), new Integer(3), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(0), new Integer(9)), new Amazon(new Integer(0), new Integer(9), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(2), new Integer(0)), new Amazon(new Integer(2), new Integer(0), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(4), new Integer(7)), new Amazon(new Integer(4), new Integer(7), new quotes.White()));
      positions.put(new Piece.Position(new Integer(7), new Integer(7)), new Amazon(new Integer(7), new Integer(7), new quotes.White()));
      positions.put(new Piece.Position(new Integer(9), new Integer(9)), new Amazon(new Integer(9), new Integer(9), new quotes.White()));
      AssertTrue(b.move(new Integer(0), new Integer(3), new Integer(5), new Integer(8)));
      AssertTrue(b.move(new Integer(3), new Integer(0), new Integer(2), new Integer(0)));
      AssertFalse(b.move(new Integer(0), new Integer(6), new Integer(0), new Integer(7)));
      b.setPositions(positions);
      AssertTrue(b.move(new Integer(0), new Integer(0), new Integer(0), new Integer(2)));
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).TestBoardMove);
    }
  }
// ***** VDMTOOLS END Name=TestBoardMove


// ***** VDMTOOLS START Name=TestBoardSetArrow KEEP=NO
  public void TestBoardSetArrow () throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).TestBoardSetArrow);
    try {
      Board b = new Board();
      Map positions = new HashMap();
      positions.put(new Piece.Position(new Integer(1), new Integer(1)), new Arrow(new Integer(1), new Integer(1)));
      positions.put(new Piece.Position(new Integer(2), new Integer(1)), new Arrow(new Integer(2), new Integer(1)));
      positions.put(new Piece.Position(new Integer(0), new Integer(0)), new Amazon(new Integer(0), new Integer(0), new quotes.White()));
      positions.put(new Piece.Position(new Integer(0), new Integer(3)), new Amazon(new Integer(0), new Integer(3), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(0), new Integer(9)), new Amazon(new Integer(0), new Integer(9), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(2), new Integer(0)), new Amazon(new Integer(2), new Integer(0), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.Black()));
      positions.put(new Piece.Position(new Integer(4), new Integer(7)), new Amazon(new Integer(4), new Integer(7), new quotes.White()));
      positions.put(new Piece.Position(new Integer(7), new Integer(7)), new Amazon(new Integer(7), new Integer(7), new quotes.White()));
      positions.put(new Piece.Position(new Integer(9), new Integer(9)), new Amazon(new Integer(9), new Integer(9), new quotes.White()));
      b.setPositions(positions);
      AssertTrue(b.move(new Integer(0), new Integer(0), new Integer(0), new Integer(2)));
      AssertTrue(b.setArrow(new Integer(0), new Integer(2), new Integer(1), new Integer(2)));
      AssertFalse(b.setArrow(new Integer(0), new Integer(3), new Integer(0), new Integer(4)));
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).TestBoardSetArrow);
    }
  }
// ***** VDMTOOLS END Name=TestBoardSetArrow


// ***** VDMTOOLS START Name=TestBoardGameOver KEEP=NO
  public void TestBoardGameOver () throws CGException {
    sentinel.entering(((TestBoardSentinel)sentinel).TestBoardGameOver);
    try {
      Board b = new Board();
      Map positions = new HashMap();
      Map p = new HashMap();
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getTurn(), new quotes.White())));
      AssertFalse(b.gameOver());
      Map rhs_7 = new HashMap();
      rhs_7.put(new Piece.Position(new Integer(0), new Integer(4)), new Arrow(new Integer(0), new Integer(4)));
      rhs_7.put(new Piece.Position(new Integer(1), new Integer(4)), new Arrow(new Integer(1), new Integer(4)));
      rhs_7.put(new Piece.Position(new Integer(1), new Integer(3)), new Arrow(new Integer(1), new Integer(3)));
      rhs_7.put(new Piece.Position(new Integer(0), new Integer(2)), new Arrow(new Integer(0), new Integer(2)));
      rhs_7.put(new Piece.Position(new Integer(1), new Integer(2)), new Arrow(new Integer(1), new Integer(2)));
      rhs_7.put(new Piece.Position(new Integer(0), new Integer(3)), new Amazon(new Integer(0), new Integer(3), new quotes.White()));
      rhs_7.put(new Piece.Position(new Integer(0), new Integer(7)), new Amazon(new Integer(0), new Integer(7), new quotes.Black()));
      positions = (Map)UTIL.clone(rhs_7);
      b.setPositions(positions);
      p = (Map)UTIL.clone(b.getPositions());
      AssertTrue(Boolean.valueOf(UTIL.equals(p, positions)));
      AssertTrue(b.gameOver());
      Map rhs_61 = new HashMap();
      rhs_61.put(new Piece.Position(new Integer(1), new Integer(0)), new Arrow(new Integer(1), new Integer(0)));
      rhs_61.put(new Piece.Position(new Integer(1), new Integer(1)), new Arrow(new Integer(1), new Integer(1)));
      rhs_61.put(new Piece.Position(new Integer(0), new Integer(1)), new Arrow(new Integer(0), new Integer(1)));
      rhs_61.put(new Piece.Position(new Integer(0), new Integer(0)), new Amazon(new Integer(0), new Integer(0), new quotes.Black()));
      rhs_61.put(new Piece.Position(new Integer(0), new Integer(7)), new Amazon(new Integer(0), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_61);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertTrue(b.gameOver());
      Map rhs_102 = new HashMap();
      rhs_102.put(new Piece.Position(new Integer(8), new Integer(8)), new Arrow(new Integer(8), new Integer(8)));
      rhs_102.put(new Piece.Position(new Integer(8), new Integer(9)), new Arrow(new Integer(8), new Integer(9)));
      rhs_102.put(new Piece.Position(new Integer(9), new Integer(8)), new Arrow(new Integer(9), new Integer(8)));
      rhs_102.put(new Piece.Position(new Integer(9), new Integer(9)), new Amazon(new Integer(9), new Integer(9), new quotes.Black()));
      rhs_102.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_102);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertTrue(b.gameOver());
      Map rhs_143 = new HashMap();
      rhs_143.put(new Piece.Position(new Integer(1), new Integer(9)), new Arrow(new Integer(1), new Integer(9)));
      rhs_143.put(new Piece.Position(new Integer(0), new Integer(8)), new Arrow(new Integer(0), new Integer(8)));
      rhs_143.put(new Piece.Position(new Integer(0), new Integer(9)), new Amazon(new Integer(0), new Integer(9), new quotes.Black()));
      rhs_143.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_143);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertFalse(b.gameOver());
      Map rhs_178 = new HashMap();
      rhs_178.put(new Piece.Position(new Integer(1), new Integer(9)), new Arrow(new Integer(1), new Integer(9)));
      rhs_178.put(new Piece.Position(new Integer(0), new Integer(8)), new Arrow(new Integer(0), new Integer(8)));
      rhs_178.put(new Piece.Position(new Integer(1), new Integer(8)), new Arrow(new Integer(1), new Integer(8)));
      rhs_178.put(new Piece.Position(new Integer(0), new Integer(9)), new Amazon(new Integer(0), new Integer(9), new quotes.Black()));
      rhs_178.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_178);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertTrue(b.gameOver());
      Map rhs_219 = new HashMap();
      rhs_219.put(new Piece.Position(new Integer(9), new Integer(1)), new Arrow(new Integer(9), new Integer(1)));
      rhs_219.put(new Piece.Position(new Integer(8), new Integer(1)), new Arrow(new Integer(8), new Integer(1)));
      rhs_219.put(new Piece.Position(new Integer(8), new Integer(0)), new Arrow(new Integer(8), new Integer(0)));
      rhs_219.put(new Piece.Position(new Integer(9), new Integer(0)), new Amazon(new Integer(9), new Integer(0), new quotes.Black()));
      rhs_219.put(new Piece.Position(new Integer(4), new Integer(7)), new Amazon(new Integer(4), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_219);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertTrue(b.gameOver());
      Map rhs_260 = new HashMap();
      rhs_260.put(new Piece.Position(new Integer(3), new Integer(4)), new Amazon(new Integer(3), new Integer(4), new quotes.Black()));
      rhs_260.put(new Piece.Position(new Integer(1), new Integer(2)), new Amazon(new Integer(1), new Integer(2), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_260);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertFalse(b.gameOver());
      Map rhs_283 = new HashMap();
      rhs_283.put(new Piece.Position(new Integer(0), new Integer(8)), new Arrow(new Integer(0), new Integer(8)));
      rhs_283.put(new Piece.Position(new Integer(1), new Integer(8)), new Arrow(new Integer(1), new Integer(8)));
      rhs_283.put(new Piece.Position(new Integer(0), new Integer(9)), new Amazon(new Integer(0), new Integer(9), new quotes.Black()));
      rhs_283.put(new Piece.Position(new Integer(3), new Integer(7)), new Amazon(new Integer(3), new Integer(7), new quotes.White()));
      positions = (Map)UTIL.clone(rhs_283);
      b.setPositions(positions);
      AssertTrue(Boolean.valueOf(UTIL.equals(b.getPositions(), positions)));
      AssertFalse(b.gameOver());
    }
    finally {
      sentinel.leaving(((TestBoardSentinel)sentinel).TestBoardGameOver);
    }
  }
// ***** VDMTOOLS END Name=TestBoardGameOver

}
;
