/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package amazonas;

/**
 *
 * @author Ana Gomes
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel1);
        jLabel1.setBounds(40, 0, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel2);
        jLabel2.setBounds(360, 40, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel3);
        jLabel3.setBounds(120, 0, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel4);
        jLabel4.setBounds(80, 0, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel5.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel5);
        jLabel5.setBounds(200, 0, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel6.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel6);
        jLabel6.setBounds(160, 0, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel7);
        jLabel7.setBounds(280, 0, 40, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel8.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel8);
        jLabel8.setBounds(240, 0, 40, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel9);
        jLabel9.setBounds(360, 0, 40, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel10.setText("jLabel1");
        jLabel10.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel10.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel10);
        jLabel10.setBounds(320, 0, 40, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel11.setText("jLabel1");
        jLabel11.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel11.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel11);
        jLabel11.setBounds(0, 40, 40, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel12.setText("jLabel1");
        jLabel12.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel12.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel12);
        jLabel12.setBounds(80, 40, 40, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        jLabel13.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel13.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel13);
        jLabel13.setBounds(40, 40, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel14.setText("jLabel1");
        jLabel14.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel14.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel14);
        jLabel14.setBounds(160, 40, 40, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        jLabel15.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel15.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel15);
        jLabel15.setBounds(120, 40, 40, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel16.setText("jLabel1");
        jLabel16.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel16.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel16);
        jLabel16.setBounds(240, 40, 40, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel17.setText("jLabel1");
        jLabel17.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel17.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel17);
        jLabel17.setBounds(200, 40, 40, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        jLabel18.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel18.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel18);
        jLabel18.setBounds(320, 40, 40, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        jLabel19.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel19.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel19);
        jLabel19.setBounds(280, 40, 40, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel20.setText("jLabel1");
        jLabel20.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel20.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel20.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel20);
        jLabel20.setBounds(0, 0, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel21.setText("jLabel1");
        jLabel21.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel21.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel21);
        jLabel21.setBounds(40, 80, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel22.setText("jLabel1");
        jLabel22.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel22.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel22.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel22);
        jLabel22.setBounds(360, 120, 40, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel23.setText("jLabel1");
        jLabel23.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel23.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel23.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel23);
        jLabel23.setBounds(120, 80, 40, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel24.setText("jLabel1");
        jLabel24.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel24.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel24.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel24);
        jLabel24.setBounds(80, 80, 40, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel25.setText("jLabel1");
        jLabel25.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel25.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel25.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel25);
        jLabel25.setBounds(200, 80, 40, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel26.setText("jLabel1");
        jLabel26.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel26.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel26.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel26);
        jLabel26.setBounds(160, 80, 40, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel27.setText("jLabel1");
        jLabel27.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel27.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel27.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel27);
        jLabel27.setBounds(280, 80, 40, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel28.setText("jLabel1");
        jLabel28.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel28.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel28.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel28);
        jLabel28.setBounds(240, 80, 40, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel29.setText("jLabel1");
        jLabel29.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel29.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel29.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel29);
        jLabel29.setBounds(360, 80, 40, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel30.setText("jLabel1");
        jLabel30.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel30.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel30.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel30);
        jLabel30.setBounds(320, 80, 40, 40);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel31.setText("jLabel1");
        jLabel31.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel31.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel31.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel31);
        jLabel31.setBounds(0, 120, 40, 40);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel32.setText("jLabel1");
        jLabel32.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel32.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel32.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel32);
        jLabel32.setBounds(80, 120, 40, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel33.setText("jLabel1");
        jLabel33.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel33.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel33.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel33);
        jLabel33.setBounds(40, 120, 40, 40);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel34.setText("jLabel1");
        jLabel34.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel34.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel34.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel34);
        jLabel34.setBounds(160, 120, 40, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel35.setText("jLabel1");
        jLabel35.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel35.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel35.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel35);
        jLabel35.setBounds(120, 120, 40, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel36.setText("jLabel1");
        jLabel36.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel36.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel36.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel36);
        jLabel36.setBounds(240, 120, 40, 40);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel37.setText("jLabel1");
        jLabel37.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel37.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel37.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel37);
        jLabel37.setBounds(200, 120, 40, 40);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel38.setText("jLabel1");
        jLabel38.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel38.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel38.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel38);
        jLabel38.setBounds(320, 120, 40, 40);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel39.setText("jLabel1");
        jLabel39.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel39.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel39.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel39);
        jLabel39.setBounds(280, 120, 40, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel40.setText("jLabel1");
        jLabel40.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel40.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel40.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel40);
        jLabel40.setBounds(0, 80, 40, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel41.setText("jLabel1");
        jLabel41.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel41.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel41.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel41);
        jLabel41.setBounds(40, 160, 40, 40);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel42.setText("jLabel1");
        jLabel42.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel42.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel42.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel42);
        jLabel42.setBounds(360, 200, 40, 40);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel43.setText("jLabel1");
        jLabel43.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel43.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel43.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel43);
        jLabel43.setBounds(120, 160, 40, 40);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel44.setText("jLabel1");
        jLabel44.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel44.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel44.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel44);
        jLabel44.setBounds(80, 160, 40, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel45.setText("jLabel1");
        jLabel45.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel45.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel45.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel45);
        jLabel45.setBounds(200, 160, 40, 40);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel46.setText("jLabel1");
        jLabel46.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel46.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel46.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel46);
        jLabel46.setBounds(160, 160, 40, 40);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel47.setText("jLabel1");
        jLabel47.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel47.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel47.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel47);
        jLabel47.setBounds(280, 160, 40, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel48.setText("jLabel1");
        jLabel48.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel48.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel48.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel48);
        jLabel48.setBounds(240, 160, 40, 40);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel49.setText("jLabel1");
        jLabel49.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel49.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel49.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel49);
        jLabel49.setBounds(360, 160, 40, 40);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel50.setText("jLabel1");
        jLabel50.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel50.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel50.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel50);
        jLabel50.setBounds(320, 160, 40, 40);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel51.setText("jLabel1");
        jLabel51.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel51.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel51.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel51);
        jLabel51.setBounds(0, 200, 40, 40);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel52.setText("jLabel1");
        jLabel52.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel52.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel52.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel52);
        jLabel52.setBounds(80, 200, 40, 40);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel53.setText("jLabel1");
        jLabel53.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel53.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel53.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel53);
        jLabel53.setBounds(40, 200, 40, 40);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel54.setText("jLabel1");
        jLabel54.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel54.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel54.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel54);
        jLabel54.setBounds(160, 200, 40, 40);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel55.setText("jLabel1");
        jLabel55.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel55.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel55.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel55);
        jLabel55.setBounds(120, 200, 40, 40);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel56.setText("jLabel1");
        jLabel56.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel56.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel56.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel56);
        jLabel56.setBounds(240, 200, 40, 40);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel57.setText("jLabel1");
        jLabel57.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel57.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel57.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel57);
        jLabel57.setBounds(200, 200, 40, 40);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel58.setText("jLabel1");
        jLabel58.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel58.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel58.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel58);
        jLabel58.setBounds(320, 200, 40, 40);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel59.setText("jLabel1");
        jLabel59.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel59.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel59.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel59);
        jLabel59.setBounds(280, 200, 40, 40);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel60.setText("jLabel1");
        jLabel60.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel60.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel60.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel60);
        jLabel60.setBounds(0, 160, 40, 40);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel61.setText("jLabel1");
        jLabel61.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel61.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel61.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel61);
        jLabel61.setBounds(40, 240, 40, 40);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel62.setText("jLabel1");
        jLabel62.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel62.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel62.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel62);
        jLabel62.setBounds(360, 280, 40, 40);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel63.setText("jLabel1");
        jLabel63.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel63.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel63.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel63);
        jLabel63.setBounds(120, 240, 40, 40);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel64.setText("jLabel1");
        jLabel64.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel64.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel64.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel64);
        jLabel64.setBounds(80, 240, 40, 40);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel65.setText("jLabel1");
        jLabel65.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel65.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel65.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel65);
        jLabel65.setBounds(200, 240, 40, 40);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel66.setText("jLabel1");
        jLabel66.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel66.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel66.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel66);
        jLabel66.setBounds(160, 240, 40, 40);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel67.setText("jLabel1");
        jLabel67.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel67.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel67.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel67);
        jLabel67.setBounds(280, 240, 40, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel68.setText("jLabel1");
        jLabel68.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel68.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel68.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel68);
        jLabel68.setBounds(240, 240, 40, 40);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel69.setText("jLabel1");
        jLabel69.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel69.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel69.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel69);
        jLabel69.setBounds(360, 240, 40, 40);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel70.setText("jLabel1");
        jLabel70.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel70.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel70.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel70);
        jLabel70.setBounds(320, 240, 40, 40);

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel71.setText("jLabel1");
        jLabel71.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel71.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel71.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel71);
        jLabel71.setBounds(0, 280, 40, 40);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel72.setText("jLabel1");
        jLabel72.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel72.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel72.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel72);
        jLabel72.setBounds(80, 280, 40, 40);

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel73.setText("jLabel1");
        jLabel73.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel73.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel73.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel73);
        jLabel73.setBounds(40, 280, 40, 40);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel74.setText("jLabel1");
        jLabel74.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel74.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel74.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel74);
        jLabel74.setBounds(160, 280, 40, 40);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel75.setText("jLabel1");
        jLabel75.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel75.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel75.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel75);
        jLabel75.setBounds(120, 280, 40, 40);

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel76.setText("jLabel1");
        jLabel76.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel76.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel76.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel76);
        jLabel76.setBounds(240, 280, 40, 40);

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel77.setText("jLabel1");
        jLabel77.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel77.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel77.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel77);
        jLabel77.setBounds(200, 280, 40, 40);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel78.setText("jLabel1");
        jLabel78.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel78.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel78.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel78);
        jLabel78.setBounds(320, 280, 40, 40);

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel79.setText("jLabel1");
        jLabel79.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel79.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel79.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel79);
        jLabel79.setBounds(280, 280, 40, 40);

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel80.setText("jLabel1");
        jLabel80.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel80.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel80.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel80);
        jLabel80.setBounds(0, 240, 40, 40);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel81.setText("jLabel1");
        jLabel81.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel81.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel81.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel81);
        jLabel81.setBounds(40, 320, 40, 40);

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel82.setText("jLabel1");
        jLabel82.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel82.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel82.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel82);
        jLabel82.setBounds(360, 360, 40, 40);

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel83.setText("jLabel1");
        jLabel83.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel83.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel83.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel83);
        jLabel83.setBounds(120, 320, 40, 40);

        jLabel84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel84.setText("jLabel1");
        jLabel84.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel84.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel84.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel84);
        jLabel84.setBounds(80, 320, 40, 40);

        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel85.setText("jLabel1");
        jLabel85.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel85.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel85.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel85);
        jLabel85.setBounds(200, 320, 40, 40);

        jLabel86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel86.setText("jLabel1");
        jLabel86.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel86.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel86.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel86);
        jLabel86.setBounds(160, 320, 40, 40);

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel87.setText("jLabel1");
        jLabel87.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel87.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel87.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel87);
        jLabel87.setBounds(280, 320, 40, 40);

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel88.setText("jLabel1");
        jLabel88.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel88.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel88.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel88);
        jLabel88.setBounds(240, 320, 40, 40);

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel89.setText("jLabel1");
        jLabel89.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel89.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel89.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel89);
        jLabel89.setBounds(360, 320, 40, 40);

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel90.setText("jLabel1");
        jLabel90.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel90.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel90.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel90);
        jLabel90.setBounds(320, 320, 40, 40);

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel91.setText("jLabel1");
        jLabel91.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel91.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel91.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel91);
        jLabel91.setBounds(0, 360, 40, 40);

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel92.setText("jLabel1");
        jLabel92.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel92.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel92.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel92);
        jLabel92.setBounds(80, 360, 40, 40);

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel93.setText("jLabel1");
        jLabel93.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel93.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel93.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel93);
        jLabel93.setBounds(40, 360, 40, 40);

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel94.setText("jLabel1");
        jLabel94.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel94.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel94.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel94);
        jLabel94.setBounds(160, 360, 40, 40);

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel95.setText("jLabel1");
        jLabel95.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel95.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel95.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel95);
        jLabel95.setBounds(120, 360, 40, 40);

        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel96.setText("jLabel1");
        jLabel96.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel96.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel96.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel96);
        jLabel96.setBounds(240, 360, 40, 40);

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel97.setText("jLabel1");
        jLabel97.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel97.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel97.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel97);
        jLabel97.setBounds(200, 360, 40, 40);

        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown_space.png"))); // NOI18N
        jLabel98.setText("jLabel1");
        jLabel98.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel98.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel98.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel98);
        jLabel98.setBounds(320, 360, 40, 40);

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel99.setText("jLabel1");
        jLabel99.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel99.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel99.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel99);
        jLabel99.setBounds(280, 360, 40, 40);

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beije_space.png"))); // NOI18N
        jLabel100.setText("jLabel1");
        jLabel100.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel100.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel100.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel100);
        jLabel100.setBounds(0, 320, 40, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    // End of variables declaration//GEN-END:variables
}
