/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Component;

/**
 *
 * @author Ana Gomes
 */
public class BoardFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form Board
     * @param parent
     */
    public BoardFrame(Component parent) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        boardPanel = new BoardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amazonas");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(435, 460));
        setMinimumSize(new java.awt.Dimension(425, 445));
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(null);

        boardPanel.setMaximumSize(new java.awt.Dimension(420, 420));
        boardPanel.setMinimumSize(new java.awt.Dimension(420, 420));
        boardPanel.setPreferredSize(new java.awt.Dimension(420, 420));
        getContentPane().add(boardPanel);
        boardPanel.setBounds(0, 0, 420, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    // End of variables declaration//GEN-END:variables

}
