/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import amazonas.*;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Ana Gomes
 */
public class BoardPanel extends javax.swing.JPanel {
    
    public BufferedImage brown = null;
    public BufferedImage beije = null;
    
    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents() throws IOException {
        
        brown = ImageIO.read(getClass().getResource("/images/brown_space.png"));
        beije = ImageIO.read(getClass().getResource("/images/beije_space.png"));
    
    }
    
    public void paintComponent (Graphics g) {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if ((i % 2 == 0 && j % 2 == 0) || (i % 2 != 0 && j % 2 != 0)) {
                    g.drawImage(beije, i*40, j*40, this);
                }
                else {
                   g.drawImage(brown, i*40, j*40, this); 
                }
                
            }
        }
    }
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
